# Generated by Django 4.0.5 on 2022-07-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='categories')),
                ('image', models.CharField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
