# Generated by Django 4.0.5 on 2022-07-11 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('image', models.CharField(max_length=255, verbose_name='Image')),
                ('price', models.CharField(max_length=100, verbose_name='Price')),
                ('attributes', models.JSONField(verbose_name='Attributes')),
                ('available', models.BooleanField(verbose_name='Available')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Category')),
            ],
        ),
    ]
