# Generated by Django 4.0.5 on 2022-07-16 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_deliveryaddress_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateField(auto_now=True, verbose_name='Date of order')),
                ('payment_mode', models.CharField(default='', max_length=255, verbose_name='Payment Mode')),
                ('delivered', models.BooleanField(default=False, verbose_name='Delivered')),
                ('address', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.deliveryaddress', verbose_name='Product')),
                ('product', models.ManyToManyField(to='api.product', verbose_name='Product')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
